In JavaScript you can pass an error object to `captureException()` to get it captured
as event. It's possible to throw strings as errors in which case no traceback
can be recorded.

```javascript
import * as Sentry from "@next/plugin-sentry";

try {
  aFunctionThatMightFail();
} catch (err) {
  Sentry.captureException(err);
}
```
